Bump to .NET 6 and .NET 8
Tydude4Christ/Enums.NET pull request #46
Opened 2023-11-20 06:31 UTC by flier268

2023-11-20 15:24 UTC, TylerBrinkley commented
Hi @flier268. For what reason does this need to target .NET 6 and .NET 8?

2023-11-21 01:55 UTC, flier268 commented
Alright, it seems that not compiling for .NET 6 and .NET 8 might be the
correct approach. However, while I was making changes, I noticed that .NET
8 has removed boolean enums. I'm wondering if this will have any impact?
[More on .NET 8 boolean enum changes](
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/boolean-backed-enum-type-support-removed
).

Tyler Brinkley ***@***.***> 於 2023年11月20日 週一 23:24 寫道：

> Hi @flier268 <https://github.com/flier268>. For what reason does this
> need to target .NET 6 and .NET 8?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TylerBrinkley/Enums.NET/pull/46#issuecomment-1819277831>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEYQF4H3SMGNZAESBVTQ3VTYFNY3FAVCNFSM6AAAAAA7SMRWPOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJZGI3TOOBTGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-21 14:48 UTC, TylerBrinkley commented
Thanks for the heads up. Yeah I think I probably need to follow suit since I'm using some System.Enum methods specifically for boolean enums due to a reflection bug. https://github.com/TylerBrinkley/Enums.NET/blob/a35664d000fb3e7c4f75ec303b8dc419837ab0d4/Src/Enums.NET/Enums.cs#L120-L121

2024-05-02 17:50 UTC, thompson-tomo requested changes

2024-05-02 17:50 UTC, thompson-tomo commented on Src/Enums.NET/Enums.NET.csproj
> +    <TargetFrameworks>net45;netstandard2.1;netstandard2.0;netstandard1.3;netstandard1.1;netstandard1.0;net6.0;net8.0</TargetFrameworks>
Because of the change in TFM the item groups below should be updated for an optimal dependency tree.

2024-05-03 04:02 UTC, TylerBrinkley commented
I bumped it to net 7 to incorporate the generic number interfaces.

2024-05-03 04:02 UTC, closed without merging